name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
        cache: 'npm'
    - run: npm install
    - run: npm install -g jest
    - run: npm test

  build-and-push-to-hub:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build Docker image
      run: |
        docker build -t my-docker-image .
        docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} -t docker.io
        docker tag my-docker-image docker.io/myusername/my-docker-image:latest
        docker push docker.io/myusername/my-docker-image:latest
      env:
        yassinedockeer: ${{ secrets.REGISTRY_USERNAME }}
        azeqs.123: ${{ secrets.REGISTRY_PASSWORD }}
